---
output: none
---

```{r setup, include=FALSE, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
#load libraries
library(highcharter)
```

```{r p_settings, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

# Create highchart theme for proteinomics.org charts
p_theme <- function(...) {
  theme <-
    list(
      colors = c("#e60049", "#0bb4ff", "#50e991", "#e6d800", "#9b19f5", "#ffa300", "#dc0ab4", "#b3d4ff", "#00bfa0"),
      chart = list(
        backgroundColor = "transparent",
        plotBorderColor = "#606063",
        style = list(
          fontFamily = "Roboto",
          color = "#3C3C3C"
        )
      ),
      plotOptions = list(
        series = list(
          marker = list(
            enabled = FALSE
          )
        )
      ),
      title = list(
        align = "left",
        style = list(
          fontWeight = "bold"
        )
      ),
      subtitle = list(
        align = "left"
      ),
      xAxis = list(
        gridLineWidth = 1,
        gridLineColor = "#D7D7D8",
        labels = list(
          style = list(
            fontFamily = "Unica One, sans-serif",
            color = "#3C3C3C"
          )
        ),
        lineColor = "#D7D7D8",
        minorGridLineColor = "#505053",
        tickColor = "#D7D7D8",
        tickWidth = 1,
        title = list(
          style = list(
            color = "#A0A0A3"
          )
        )
      ),
      yAxis = list(
        gridLineColor = "#D7D7D8",
        labels = list(
          style = list(
            fontFamily = "Unica One, sans-serif",
            color = "#3C3C3C"
          )
        ),
        lineColor = "#D7D7D8",
        minorGridLineColor = "#505053",
        tickColor = "#D7D7D8",
        tickWidth = 1,
        title = list(
          style = list(
            color = "#A0A0A3"
          )
        )
      ),
      tooltip = list(
        backgroundColor = "rgba(0, 0, 0, 0.85)",
        style = list(
          color = "#F0F0F0"
        )
      ),
      legend = list(
        itemStyle = list(
          color = "#3C3C3C"
        ),
        itemHiddenStyle = list(
          color = "#606063"
        )
      ),
      credits = list(
        style = list(
          color = "#666"
        )
      ),
      labels = list(
        style = list(
          color = "#D7D7D8"
        )
      ),
      legendBackgroundColor = "rgba(0, 0, 0, 0.5)",
      background2 = "#505053",
      dataLabelsColor = "#B0B0B3",
      textColor = "#C0C0C0",
      contrastTextColor = "#F0F0F3",
      maskColor = "rgba(255,255,255,0.3)"
    )

  theme <- structure(theme, class = "hc_theme")

  if (length(list(...)) > 0) {
    theme <- hc_theme_merge(
      theme,
      hc_theme(...)
    )
  }

  theme
}

write_rds(p_theme, file="p_theme.rds")

# Set highchart options

p_chart_opts <- function(...) {
lang <- getOption("highcharter.lang")
lang$numericSymbols = c("k", "M", "B", "T", "P", "E")
p_chart_opts <- options(highcharter.lang = lang)
}

write_rds(p_chart_opts, file = "p_chart_opts.rds")



```